# -*- coding: utf-8 -*-
"""Handwritten Digit Recognition (MNIST)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16n--H0SRMOoDDVa_85VTcJlIHD4rTCzf
"""

# 1. Import libraries
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

# 2. Load Dataset (MNIST)
minst = tf.keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = minst.load_data()

# 3. Preprocess (Normalize pixel values between 0 and 1) and reshape for CNN
X_train, X_test = X_train / 255.0, X_test / 255.0
# Reshape data to include a channel dimension for CNN (e.g., (60000, 28, 28, 1))
X_train = X_train.reshape((X_train.shape[0], 28, 28, 1))
X_test = X_test.reshape((X_test.shape[0], 28, 28, 1))

# 4. Build Convolutional Neural Network (CNN)
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(10, activation='softmax')
    ])

# 5. Compile and Train
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

print("Training started...")
model.fit(X_train, y_train, epochs=5)

# 6. Assessment Results
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print(f"\nTest Accuracy: {test_acc*100:.2f}%")

# 7. Visualize a prediction
prediction = model.predict(X_test[:1])
print(f"Predicted Digit: {prediction.argmax()}")
plt.imshow(X_test[0].reshape(28, 28), cmap='gray') # Reshape back for plotting
plt.show()